#!/bin/sh

BASEDIR=`dirname "$0" 2>/dev/null`

if test -n "$JAVA_HOME"; then
    JAVA="$JAVA_HOME/bin/java"
elif command -v java > /dev/null; then
    JAVA=java
else
    echo "Java not found! Please install the Java JDK https://openjdk.java.net/"
    echo "Press any key to exit"
    read
    exit 1
fi

$JAVA -jar $BASEDIR/partiql-cli.jar