package org.partiql.cli

import org.partiql.spi.errors.PError

/**
 * This is used by PicoCLI for de-serializing user-input for converting warnings to errors.
 *
 * @see MainCommand.warningsAsErrors
 */
enum class ErrorCodeString(val code: Int) {
    ALL(-1),
    INTERNAL_ERROR(PError.INTERNAL_ERROR),
    UNRECOGNIZED_TOKEN(PError.UNRECOGNIZED_TOKEN),
    UNEXPECTED_TOKEN(PError.UNEXPECTED_TOKEN),
    PATH_KEY_NEVER_SUCCEEDS(PError.PATH_KEY_NEVER_SUCCEEDS),
    PATH_SYMBOL_NEVER_SUCCEEDS(PError.PATH_SYMBOL_NEVER_SUCCEEDS),
    PATH_INDEX_NEVER_SUCCEEDS(PError.PATH_INDEX_NEVER_SUCCEEDS),
    FEATURE_NOT_SUPPORTED(PError.FEATURE_NOT_SUPPORTED),
    UNDEFINED_CAST(PError.UNDEFINED_CAST),
    FUNCTION_NOT_FOUND(PError.FUNCTION_NOT_FOUND),
    FUNCTION_TYPE_MISMATCH(PError.FUNCTION_TYPE_MISMATCH),
    VAR_REF_NOT_FOUND(PError.VAR_REF_NOT_FOUND),
    VAR_REF_AMBIGUOUS(PError.VAR_REF_AMBIGUOUS),
    TYPE_UNEXPECTED(PError.TYPE_UNEXPECTED),
    ALWAYS_MISSING(PError.ALWAYS_MISSING),
    INVALID_EXCLUDE_PATH(PError.INVALID_EXCLUDE_PATH),
    CARDINALITY_VIOLATION(PError.CARDINALITY_VIOLATION),
    NUMERIC_VALUE_OUT_OF_RANGE(PError.NUMERIC_VALUE_OUT_OF_RANGE),
    INVALID_CHAR_VALUE_FOR_CAST(PError.INVALID_CHAR_VALUE_FOR_CAST),
    DIVISION_BY_ZERO(PError.DIVISION_BY_ZERO),
    DEGREE_VIOLATION_SCALAR_SUBQUERY(PError.DEGREE_VIOLATION_SCALAR_SUBQUERY),
    EXPERIMENTAL(PError.EXPERIMENTAL),
}
