CREATE FUNCTION "SUBSTRING"(
    S CHARACTER ( CML ),
START NUMERIC ( MP, 0 ),
LENGTH NUMERIC ( MP, 0 ) )
RETURNS CHARACTER VARYING ( CML )
SPECIFIC SUBSTRING1
RETURN SUBSTRING ( S FROM START FOR LENGTH ) ;
