CREATE FUNCTION "SUBSTRING"(
    S CHARACTER VARYING ( CML ),
START NUMERIC ( MP, 0 ),
LENGTH NUMERIC ( MP, 0 ) )
RETURNS CHARACTER VARYING ( CML )
SPECIFIC SUBSTRING2
RETURN SUBSTRING ( S FROM START FOR LENGTH ) ;
