-- [cast] ---------

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (INT8))
    RETURNS INT8
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (INT16))
    RETURNS INT16
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (INT32))
    RETURNS INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (INT64))
    RETURNS INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (INT))
    RETURNS INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (DECIMAL))
    RETURNS DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (FLOAT32))
    RETURNS FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (FLOAT64))
    RETURNS FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (CHAR))
    RETURNS CHAR
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_INT8))
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_INT16))
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_INT32))
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_CHAR))
    RETURNS NULLABLE_CHAR
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BOOL
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_INT8))
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_INT16))
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_INT32))
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_CHAR))
    RETURNS NULLABLE_CHAR
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BOOL
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (INT8))
    RETURNS INT8
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (INT16))
    RETURNS INT16
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (INT32))
    RETURNS INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (INT64))
    RETURNS INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (INT))
    RETURNS INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (DECIMAL))
    RETURNS DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (FLOAT32))
    RETURNS FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (FLOAT64))
    RETURNS FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_INT8))
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_INT16))
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_INT32))
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT8
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_INT8))
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_INT16))
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_INT32))
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT8
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (INT16))
    RETURNS INT16
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (INT32))
    RETURNS INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (INT64))
    RETURNS INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (INT))
    RETURNS INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (DECIMAL))
    RETURNS DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (FLOAT32))
    RETURNS FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (FLOAT64))
    RETURNS FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_INT16))
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_INT32))
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT16
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_INT16))
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_INT32))
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT16
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (INT32))
    RETURNS INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (INT64))
    RETURNS INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (INT))
    RETURNS INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (DECIMAL))
    RETURNS DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (FLOAT32))
    RETURNS FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (FLOAT64))
    RETURNS FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (NULLABLE_INT32))
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT32
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT32
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT32
        TYPE TYPE (NULLABLE_INT32))
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT32
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT32
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT32
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT32
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT32
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT32
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT32
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (INT64))
    RETURNS INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (INT))
    RETURNS INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (DECIMAL))
    RETURNS DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (FLOAT32))
    RETURNS FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (FLOAT64))
    RETURNS FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT64
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT64
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT64
        TYPE TYPE (NULLABLE_INT64))
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT64
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT64
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT64
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT64
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT64
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT64
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (INT))
    RETURNS INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (DECIMAL))
    RETURNS DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (FLOAT32))
    RETURNS FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (FLOAT64))
    RETURNS FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE INT
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT
        TYPE TYPE (NULLABLE_INT))
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_INT
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (DECIMAL))
    RETURNS DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (FLOAT32))
    RETURNS FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (FLOAT64))
    RETURNS FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE DECIMAL
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_DECIMAL
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_DECIMAL
        TYPE TYPE (NULLABLE_DECIMAL))
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_DECIMAL
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_DECIMAL
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_DECIMAL
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_DECIMAL
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (FLOAT32))
    RETURNS FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (FLOAT64))
    RETURNS FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT32
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_FLOAT32
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_FLOAT32
        TYPE TYPE (NULLABLE_FLOAT32))
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_FLOAT32
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_FLOAT32
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_FLOAT32
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT64
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT64
        TYPE TYPE (FLOAT64))
    RETURNS FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT64
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT64
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT64
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT64
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT64
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE FLOAT64
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_FLOAT64
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_FLOAT64
        TYPE TYPE (NULLABLE_FLOAT64))
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_FLOAT64
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_FLOAT64
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CHAR
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CHAR
        TYPE TYPE (CHAR))
    RETURNS CHAR
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CHAR
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CHAR
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CHAR
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CHAR
        TYPE TYPE (NULLABLE_CHAR))
    RETURNS NULLABLE_CHAR
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CHAR
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CHAR
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_CHAR
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_CHAR
        TYPE TYPE (NULLABLE_CHAR))
    RETURNS NULLABLE_CHAR
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_CHAR
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_CHAR
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRING
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRING
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRING
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRING
        TYPE TYPE (CLOB))
    RETURNS CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRING
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRING
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRING
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRING
        TYPE TYPE (NULLABLE_CLOB))
    RETURNS NULLABLE_CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_STRING
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_STRING
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_STRING
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_STRING
        TYPE TYPE (CLOB))
    RETURNS CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_STRING
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_STRING
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_STRING
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_STRING
        TYPE TYPE (NULLABLE_CLOB))
    RETURNS NULLABLE_CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SYMBOL
        TYPE TYPE (BOOL))
    RETURNS BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SYMBOL
        TYPE TYPE (STRING))
    RETURNS STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SYMBOL
        TYPE TYPE (SYMBOL))
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SYMBOL
        TYPE TYPE (CLOB))
    RETURNS CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SYMBOL
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SYMBOL
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SYMBOL
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SYMBOL
        TYPE TYPE (NULLABLE_CLOB))
    RETURNS NULLABLE_CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_SYMBOL
        TYPE TYPE (NULLABLE_BOOL))
    RETURNS NULLABLE_BOOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_SYMBOL
        TYPE TYPE (NULLABLE_STRING))
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_SYMBOL
        TYPE TYPE (NULLABLE_SYMBOL))
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_SYMBOL
        TYPE TYPE (NULLABLE_CLOB))
    RETURNS NULLABLE_CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CLOB
        TYPE TYPE (CLOB))
    RETURNS CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE CLOB
        TYPE TYPE (NULLABLE_CLOB))
    RETURNS NULLABLE_CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_CLOB
        TYPE TYPE (NULLABLE_CLOB))
    RETURNS NULLABLE_CLOB
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE LIST
        TYPE TYPE (BAG))
    RETURNS BAG
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE LIST
        TYPE TYPE (LIST))
    RETURNS LIST
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE LIST
        TYPE TYPE (SEXP))
    RETURNS SEXP
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE LIST
        TYPE TYPE (NULLABLE_BAG))
    RETURNS NULLABLE_BAG
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE LIST
        TYPE TYPE (NULLABLE_LIST))
    RETURNS NULLABLE_LIST
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE LIST
        TYPE TYPE (NULLABLE_SEXP))
    RETURNS NULLABLE_SEXP
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_LIST
        TYPE TYPE (NULLABLE_BAG))
    RETURNS NULLABLE_BAG
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_LIST
        TYPE TYPE (NULLABLE_LIST))
    RETURNS NULLABLE_LIST
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_LIST
        TYPE TYPE (NULLABLE_SEXP))
    RETURNS NULLABLE_SEXP
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BAG
        TYPE TYPE (BAG))
    RETURNS BAG
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE BAG
        TYPE TYPE (NULLABLE_BAG))
    RETURNS NULLABLE_BAG
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_BAG
        TYPE TYPE (NULLABLE_BAG))
    RETURNS NULLABLE_BAG
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SEXP
        TYPE TYPE (BAG))
    RETURNS BAG
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SEXP
        TYPE TYPE (LIST))
    RETURNS LIST
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SEXP
        TYPE TYPE (SEXP))
    RETURNS SEXP
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SEXP
        TYPE TYPE (NULLABLE_BAG))
    RETURNS NULLABLE_BAG
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SEXP
        TYPE TYPE (NULLABLE_LIST))
    RETURNS NULLABLE_LIST
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE SEXP
        TYPE TYPE (NULLABLE_SEXP))
    RETURNS NULLABLE_SEXP
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_SEXP
        TYPE TYPE (NULLABLE_BAG))
    RETURNS NULLABLE_BAG
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_SEXP
        TYPE TYPE (NULLABLE_LIST))
    RETURNS NULLABLE_LIST
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_SEXP
        TYPE TYPE (NULLABLE_SEXP))
    RETURNS NULLABLE_SEXP
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRUCT
        TYPE TYPE (STRUCT))
    RETURNS STRUCT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE STRUCT
        TYPE TYPE (NULLABLE_STRUCT))
    RETURNS NULLABLE_STRUCT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );

CREATE FUNCTION "CAST"(
    VALUE NULLABLE_STRUCT
        TYPE TYPE (NULLABLE_STRUCT))
    RETURNS NULLABLE_STRUCT
    SPECIFIC -
  RETURN CAST ( VALUE, TYPE );
