--- [not] ---------

CREATE FUNCTION "NOT"(
    VALUE BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NOT ( VALUE );

CREATE FUNCTION "NOT"(
    VALUE BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NOT ( VALUE );


--- [pos] ---------

CREATE FUNCTION "POS"(
    VALUE INT8)
    RETURNS INT8
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE NULLABLE_INT8)
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE INT16)
    RETURNS INT16
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE NULLABLE_INT16)
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE INT32)
    RETURNS INT32
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE NULLABLE_INT32)
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE INT64)
    RETURNS INT64
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE NULLABLE_INT64)
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE INT)
    RETURNS INT
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE NULLABLE_INT)
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE DECIMAL)
    RETURNS DECIMAL
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE NULLABLE_DECIMAL)
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE FLOAT32)
    RETURNS FLOAT32
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE NULLABLE_FLOAT32)
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE FLOAT64)
    RETURNS FLOAT64
    SPECIFIC -
  RETURN POS ( VALUE );

CREATE FUNCTION "POS"(
    VALUE NULLABLE_FLOAT64)
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN POS ( VALUE );


--- [neg] ---------

CREATE FUNCTION "NEG"(
    VALUE INT8)
    RETURNS INT8
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE NULLABLE_INT8)
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE INT16)
    RETURNS INT16
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE NULLABLE_INT16)
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE INT32)
    RETURNS INT32
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE NULLABLE_INT32)
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE INT64)
    RETURNS INT64
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE NULLABLE_INT64)
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE INT)
    RETURNS INT
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE NULLABLE_INT)
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE DECIMAL)
    RETURNS DECIMAL
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE NULLABLE_DECIMAL)
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE FLOAT32)
    RETURNS FLOAT32
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE NULLABLE_FLOAT32)
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE FLOAT64)
    RETURNS FLOAT64
    SPECIFIC -
  RETURN NEG ( VALUE );

CREATE FUNCTION "NEG"(
    VALUE NULLABLE_FLOAT64)
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN NEG ( VALUE );


--- [eq] ---------

CREATE FUNCTION "EQ"(
    LHS NULL
        RHS NULL)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS MISSING
        RHS MISSING)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS BOOL
        RHS BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_BOOL
        RHS NULLABLE_BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS INT8
        RHS INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS INT16
        RHS INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS INT32
        RHS INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS INT64
        RHS INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS INT
        RHS INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS CHAR
        RHS CHAR)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_CHAR
        RHS NULLABLE_CHAR)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS SYMBOL
        RHS SYMBOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_SYMBOL
        RHS NULLABLE_SYMBOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS STRING
        RHS STRING)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_STRING
        RHS NULLABLE_STRING)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS CLOB
        RHS CLOB)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_CLOB
        RHS NULLABLE_CLOB)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS BINARY
        RHS BINARY)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_BINARY
        RHS NULLABLE_BINARY)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS BYTE
        RHS BYTE)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_BYTE
        RHS NULLABLE_BYTE)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS BLOB
        RHS BLOB)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_BLOB
        RHS NULLABLE_BLOB)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS DATE
        RHS DATE)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_DATE
        RHS NULLABLE_DATE)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS TIME
        RHS TIME)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_TIME
        RHS NULLABLE_TIME)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS TIMESTAMP
        RHS TIMESTAMP)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_TIMESTAMP
        RHS NULLABLE_TIMESTAMP)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS INTERVAL
        RHS INTERVAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_INTERVAL
        RHS NULLABLE_INTERVAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS LIST
        RHS LIST)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_LIST
        RHS NULLABLE_LIST)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS BAG
        RHS BAG)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_BAG
        RHS NULLABLE_BAG)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS SEXP
        RHS SEXP)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_SEXP
        RHS NULLABLE_SEXP)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS STRUCT
        RHS STRUCT)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS NULLABLE_STRUCT
        RHS NULLABLE_STRUCT)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );

CREATE FUNCTION "EQ"(
    LHS GRAPH
        RHS GRAPH)
    RETURNS BOOL
    SPECIFIC -
  RETURN EQ ( LHS, RHS );


--- [neq] ---------

CREATE FUNCTION "NEQ"(
    LHS NULL
        RHS NULL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS MISSING
        RHS MISSING)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS BOOL
        RHS BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_BOOL
        RHS NULLABLE_BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS INT8
        RHS INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS INT16
        RHS INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS INT32
        RHS INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS INT64
        RHS INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS INT
        RHS INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS CHAR
        RHS CHAR)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_CHAR
        RHS NULLABLE_CHAR)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS SYMBOL
        RHS SYMBOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_SYMBOL
        RHS NULLABLE_SYMBOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS STRING
        RHS STRING)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_STRING
        RHS NULLABLE_STRING)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS CLOB
        RHS CLOB)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_CLOB
        RHS NULLABLE_CLOB)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS BINARY
        RHS BINARY)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_BINARY
        RHS NULLABLE_BINARY)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS BYTE
        RHS BYTE)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_BYTE
        RHS NULLABLE_BYTE)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS BLOB
        RHS BLOB)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_BLOB
        RHS NULLABLE_BLOB)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS DATE
        RHS DATE)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_DATE
        RHS NULLABLE_DATE)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS TIME
        RHS TIME)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_TIME
        RHS NULLABLE_TIME)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS TIMESTAMP
        RHS TIMESTAMP)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_TIMESTAMP
        RHS NULLABLE_TIMESTAMP)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS INTERVAL
        RHS INTERVAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_INTERVAL
        RHS NULLABLE_INTERVAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS LIST
        RHS LIST)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_LIST
        RHS NULLABLE_LIST)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS BAG
        RHS BAG)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_BAG
        RHS NULLABLE_BAG)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS SEXP
        RHS SEXP)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_SEXP
        RHS NULLABLE_SEXP)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS STRUCT
        RHS STRUCT)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS NULLABLE_STRUCT
        RHS NULLABLE_STRUCT)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );

CREATE FUNCTION "NEQ"(
    LHS GRAPH
        RHS GRAPH)
    RETURNS BOOL
    SPECIFIC -
  RETURN NEQ ( LHS, RHS );


--- [and] ---------

CREATE FUNCTION "AND"(
    LHS BOOL
        RHS BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN AND ( LHS, RHS );

CREATE FUNCTION "AND"(
    LHS NULLABLE_BOOL
        RHS NULLABLE_BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN AND ( LHS, RHS );


--- [or] ---------

CREATE FUNCTION "OR"(
    LHS BOOL
        RHS BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN OR ( LHS, RHS );

CREATE FUNCTION "OR"(
    LHS NULLABLE_BOOL
        RHS NULLABLE_BOOL)
    RETURNS BOOL
    SPECIFIC -
  RETURN OR ( LHS, RHS );


--- [lt] ---------

CREATE FUNCTION "LT"(
    LHS INT8
        RHS INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS INT16
        RHS INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS INT32
        RHS INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS INT64
        RHS INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS INT
        RHS INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );

CREATE FUNCTION "LT"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN LT ( LHS, RHS );


--- [lte] ---------

CREATE FUNCTION "LTE"(
    LHS INT8
        RHS INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS INT16
        RHS INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS INT32
        RHS INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS INT64
        RHS INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS INT
        RHS INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );

CREATE FUNCTION "LTE"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN LTE ( LHS, RHS );


--- [gt] ---------

CREATE FUNCTION "GT"(
    LHS INT8
        RHS INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS INT16
        RHS INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS INT32
        RHS INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS INT64
        RHS INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS INT
        RHS INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );

CREATE FUNCTION "GT"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN GT ( LHS, RHS );


--- [gte] ---------

CREATE FUNCTION "GTE"(
    LHS INT8
        RHS INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS INT16
        RHS INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS INT32
        RHS INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS INT64
        RHS INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS INT
        RHS INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );

CREATE FUNCTION "GTE"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS BOOL
    SPECIFIC -
  RETURN GTE ( LHS, RHS );


--- [plus] ---------

CREATE FUNCTION "PLUS"(
    LHS INT8
        RHS INT8)
    RETURNS INT8
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS INT16
        RHS INT16)
    RETURNS INT16
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS INT32
        RHS INT32)
    RETURNS INT32
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS INT64
        RHS INT64)
    RETURNS INT64
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS INT
        RHS INT)
    RETURNS INT
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS DECIMAL
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS FLOAT32
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS FLOAT64
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );

CREATE FUNCTION "PLUS"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN PLUS ( LHS, RHS );


--- [minus] ---------

CREATE FUNCTION "MINUS"(
    LHS INT8
        RHS INT8)
    RETURNS INT8
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS INT16
        RHS INT16)
    RETURNS INT16
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS INT32
        RHS INT32)
    RETURNS INT32
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS INT64
        RHS INT64)
    RETURNS INT64
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS INT
        RHS INT)
    RETURNS INT
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS DECIMAL
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS FLOAT32
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS FLOAT64
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );

CREATE FUNCTION "MINUS"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN MINUS ( LHS, RHS );


--- [times] ---------

CREATE FUNCTION "TIMES"(
    LHS INT8
        RHS INT8)
    RETURNS INT8
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS INT16
        RHS INT16)
    RETURNS INT16
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS INT32
        RHS INT32)
    RETURNS INT32
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS INT64
        RHS INT64)
    RETURNS INT64
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS INT
        RHS INT)
    RETURNS INT
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS DECIMAL
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS FLOAT32
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS FLOAT64
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );

CREATE FUNCTION "TIMES"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN TIMES ( LHS, RHS );


--- [div] ---------

CREATE FUNCTION "DIV"(
    LHS INT8
        RHS INT8)
    RETURNS INT8
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS INT16
        RHS INT16)
    RETURNS INT16
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS INT32
        RHS INT32)
    RETURNS INT32
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS INT64
        RHS INT64)
    RETURNS INT64
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS INT
        RHS INT)
    RETURNS INT
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS DECIMAL
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS FLOAT32
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS FLOAT64
    SPECIFIC -
  RETURN DIV ( LHS, RHS );

CREATE FUNCTION "DIV"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN DIV ( LHS, RHS );


--- [mod] ---------

CREATE FUNCTION "MOD"(
    LHS INT8
        RHS INT8)
    RETURNS INT8
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS NULLABLE_INT8
        RHS NULLABLE_INT8)
    RETURNS NULLABLE_INT8
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS INT16
        RHS INT16)
    RETURNS INT16
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS NULLABLE_INT16
        RHS NULLABLE_INT16)
    RETURNS NULLABLE_INT16
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS INT32
        RHS INT32)
    RETURNS INT32
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS NULLABLE_INT32
        RHS NULLABLE_INT32)
    RETURNS NULLABLE_INT32
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS INT64
        RHS INT64)
    RETURNS INT64
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS NULLABLE_INT64
        RHS NULLABLE_INT64)
    RETURNS NULLABLE_INT64
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS INT
        RHS INT)
    RETURNS INT
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS NULLABLE_INT
        RHS NULLABLE_INT)
    RETURNS NULLABLE_INT
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS DECIMAL
        RHS DECIMAL)
    RETURNS DECIMAL
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS NULLABLE_DECIMAL
        RHS NULLABLE_DECIMAL)
    RETURNS NULLABLE_DECIMAL
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS FLOAT32
        RHS FLOAT32)
    RETURNS FLOAT32
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS NULLABLE_FLOAT32
        RHS NULLABLE_FLOAT32)
    RETURNS NULLABLE_FLOAT32
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS FLOAT64
        RHS FLOAT64)
    RETURNS FLOAT64
    SPECIFIC -
  RETURN MOD ( LHS, RHS );

CREATE FUNCTION "MOD"(
    LHS NULLABLE_FLOAT64
        RHS NULLABLE_FLOAT64)
    RETURNS NULLABLE_FLOAT64
    SPECIFIC -
  RETURN MOD ( LHS, RHS );


--- [concat] ---------

CREATE FUNCTION "CONCAT"(
    LHS SYMBOL
        RHS SYMBOL)
    RETURNS SYMBOL
    SPECIFIC -
  RETURN CONCAT ( LHS, RHS );

CREATE FUNCTION "CONCAT"(
    LHS NULLABLE_SYMBOL
        RHS NULLABLE_SYMBOL)
    RETURNS NULLABLE_SYMBOL
    SPECIFIC -
  RETURN CONCAT ( LHS, RHS );

CREATE FUNCTION "CONCAT"(
    LHS STRING
        RHS STRING)
    RETURNS STRING
    SPECIFIC -
  RETURN CONCAT ( LHS, RHS );

CREATE FUNCTION "CONCAT"(
    LHS NULLABLE_STRING
        RHS NULLABLE_STRING)
    RETURNS NULLABLE_STRING
    SPECIFIC -
  RETURN CONCAT ( LHS, RHS );
