package org.partiql.runner

import org.junit.jupiter.api.extension.RegisterExtension
import org.partiql.eval.PartiQLResult
import org.partiql.eval.PartiQLStatement
import org.partiql.lang.eval.CompileOptions
import org.partiql.lang.eval.TypingMode
import org.partiql.runner.executor.EvalExecutor
import org.partiql.runner.report.ReportGenerator
import org.partiql.runner.test.TestRunner

class ConformanceTestEval : ConformanceTestBase<PartiQLStatement<*>, PartiQLResult>() {
    companion object {
        @JvmStatic
        @RegisterExtension
        val reporter = ReportGenerator("eval")

        private val COERCE_EVAL_MODE_COMPILE_OPTIONS = CompileOptions.build { typingMode(TypingMode.PERMISSIVE) }
        private val ERROR_EVAL_MODE_COMPILE_OPTIONS = CompileOptions.build { typingMode(TypingMode.LEGACY) }
    }

    private val factory = EvalExecutor.Factory
    override val runner = TestRunner(factory)

    /**
     * Currently, the [ConformanceTestEval] only skips GPML-related tests.
     */
    override val skipListForEvaluation: List<Pair<String, CompileOptions>>
        get() = gpmlTests + testsToFix

    override val skipListForEquivalence: List<Pair<String, CompileOptions>> = emptyList()

    /**
     * TODO: ADD SUPPORT FOR THESE
     * Variable does not exist.
     */
    private val aliasTests: List<Pair<String, CompileOptions>> = listOf(
        Pair("testing alias support", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("testing alias support", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("testing nested alias support", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("testing nested alias support", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("group and order by count", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("group and order by count", ERROR_EVAL_MODE_COMPILE_OPTIONS),
    )

    /**
     * TODO: ADD SUPPORT FOR THESE
     * Wrong precision/scale
     */
    private val arithmeticCases = listOf(
        Pair("division with mixed StaticType", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("division with mixed StaticType", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("repeatingDecimal", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("repeatingDecimal", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("repeatingDecimalHigherPrecision", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("repeatingDecimalHigherPrecision", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("divDecimalInt", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("divDecimalInt", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("subtractionOutOfAllowedPrecision", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("subtractionOutOfAllowedPrecision", ERROR_EVAL_MODE_COMPILE_OPTIONS),
    )

    private val testsToFix: List<Pair<String, CompileOptions>> = aliasTests + arithmeticCases

    /**
     * This holds all of the Graph Pattern Matching Language conformance tests. The new evaluator does not yet support
     * their evaluation.
     */
    private val gpmlTests: List<Pair<String, CompileOptions>> = listOf(
        Pair("Right with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with variables and label", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with variables and label", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with variables and label", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right with variables and label", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with variables and label", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with variables and label", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with variables and label", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Undirected with variables and label", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with variables and labels", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with variables and labels", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with variables and labels", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Right+undirected with variables and labels", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with variables and label", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with variables and label", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with variables and label", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+undirected with variables and label", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected with variables", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected with variables", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected with spots", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected with spots", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected shorthand", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("Left+right+undirected shorthand", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N0E0 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1E0 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH ~[y]~ )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH ~[y]~ )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH ~[y]~ )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH ~[y]~ )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x)~[y]~(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x)~[y]~(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x)~[y]~(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x)~[y]~(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x)~[y]~(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x)~[y]~(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x)~[y]~(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x)~[y]~(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1U1 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N1D2 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2E0 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D1 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH ~[y]~ )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH ~[y]~ )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH ~[y]~ )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH ~[y]~ )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x)~[y]~(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x)~[y]~(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x)~[y]~(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x)~[y]~(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x)~[y]~(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x)~[y]~(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x)~[y]~(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x)~[y]~(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)~[y1]~(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)~[y1]~(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)~[y1]~(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)~[y1]~(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)-[y1]-(x2)~[y2]~(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)-[y1]-(x2)~[y2]~(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)-[y1]-(x2)~[y2]~(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)-[y1]-(x2)~[y2]~(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U1 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2 MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH -[y]-> )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH -[y]-> )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x)-[y]->(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x)-[y]->(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x)-[y]->(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x)-[y]->(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]->(x1) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]->(x1) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]->(x1) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]->(x1) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]->(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]-(x2)-[y2]->(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2D2c MATCH (x1)-[y1]-(x2)-[y2]-(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x))", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x))", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH ~[y]~ )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH ~[y]~ )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH ~[y]~ )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH ~[y]~ )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x)~[y]~(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x)~[y]~(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x)~[y]~(z) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x)~[y]~(z) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x)~[y]~(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x)~[y]~(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x)~[y]~(x) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x)~[y]~(x) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x1)~[y1]~(x2)~[y2]~(x3) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x1)~[y1]~(x2)~[y2]~(x1) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x1)~[y1]~(x2)~[y2]~(x1) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x1)~[y1]~(x2)~[y2]~(x1) )", COERCE_EVAL_MODE_COMPILE_OPTIONS),
        Pair("(N2U2 MATCH (x1)~[y1]~(x2)~[y2]~(x1) )", ERROR_EVAL_MODE_COMPILE_OPTIONS),
    )
}
