/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "partiql-upgrades"

include(
    "v0.1-to-v0.2-upgrade:examples",
    "v0.1-to-v0.2-upgrade:upgraded-examples",
    "v0.2-to-v0.3-upgrade:examples",
    "v0.2-to-v0.3-upgrade:upgraded-examples",
    "v0.3-to-v0.4-upgrade:examples",
    "v0.3-to-v0.4-upgrade:upgraded-examples",
    "v0.4-to-v0.5-upgrade:examples",
    "v0.4-to-v0.5-upgrade:upgraded-examples",
    "v0.5-to-v0.6-upgrade:examples",
    "v0.5-to-v0.6-upgrade:upgraded-examples",
    "v0.6-to-v0.7-upgrade:examples",
    "v0.6-to-v0.7-upgrade:upgraded-examples",
    "v0.7-to-v0.8-upgrade:examples",
    "v0.7-to-v0.8-upgrade:upgraded-examples"
)
