CREATE FUNCTION "SUBSTRING"(
    S BIT VARYING ( BML ),
START NUMERIC ( MP, 0 ),
LENGTH NUMERIC ( MP, 0 ) )
RETURNS BIT VARYING ( BML )
SPECIFIC SUBSTRING6
RETURN SUBSTRING ( S FROM START FOR LENGTH ) ;
