##
# JMH Benchmarks workflow.
# - Runs the JMH benchmarks and places the results in the project's GH pages.
# - On alert, notifies the PartiQL team and the commit author
##

name: JMH Benchmarks

on:
  push:
    branches:
      - main

env:
  JMH_RESULTS_PATH_FROM_ROOT: lang/build/reports/jmh/results.json
  JMH_RESULTS_PATH: build/reports/jmh/results.json

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run JMH benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Print Environment Variables
        run: |
          echo "Owner: @${{ env.GITHUB_REPOSITORY_OWNER }}"
          echo "Repo: ${{ env.GITHUB_REPOSITORY }}"
          echo "Actor: @${{ env.GITHUB_ACTOR }}"
          echo "Author: @${{ github.event.commits[0].author.username }}"

      - name: Run Benchmark
        run: |
          ./gradlew :lang:jmh \
            -Pinclude="PartiQLBenchmark" \
            -Piterations=3 \
            -PwarmupIterations=3 \
            -Pfork=1 \
            -PresultsFile="${{ env.JMH_RESULTS_PATH }}"

      - name: Store Benchmark Result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: JMH Benchmark
          tool: 'jmh'
          output-file-path: ${{ env.JMH_RESULTS_PATH_FROM_ROOT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '110%'
          fail-on-alert: true
          comment-on-alert: true
          alert-comment-cc-users: '@${{ github.event.commits[0].author.username }}'
