
name: Documentation

on: push

jobs: 
  build_via_pandoc:
    runs-on: ubuntu-18.04
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Build`
        uses: docker://therapon/pandoc2:2.0
        with:
          entrypoint: ./docker-entrypoint.sh
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/webapp # The folder the action should deploy.
