# Builds documentation and deplouys to gh-pages branch 
# URL should be 
# https://partiql.github.io/partiql-lang-kotlin/user-guide.html
# https://partiql.github.io/partiql-lang-kotlin/user-guide.pdf
# https://partiql.github.io/partiql-lang-kotlin/dev-guide.html
# https://partiql.github.io/partiql-lang-kotlin/dev-guide.pdf
# https://partiql.github.io/partiql-lang-kotlin/tutorial.html
# https://partiql.github.io/partiql-lang-kotlin/tutorial.pdf
name: Release Documentation

on:
  release:
    types: [published,prereleased]

jobs: 
  build_via_pandoc:
    runs-on: ubuntu-18.04
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Build
        uses: docker://partiqlteam/pandoc:1.0
        with:
          entrypoint: ./docker-entrypoint.sh
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/webapp # The folder the action should deploy.
